export * as trophy from './noto-trophy.png';
export * as star2 from './star-2.png';
export * as tabBorderRight from './tab-border-right.png';
export * as tabBorderLeft from './tab-border-left.png';
//=========dummy avatar==========//
export * as dummyGalaxy from './galaxy-dummy.jpeg'
export * as dummyAvtSao from './dummy-avt-sao.png'
export * as dummyAvtAutumn3 from './dummy-avt-autumn-3.png'
export * as dummyAvt from './dummy-avt.png'
export * as dummyAvt1 from './dummy-avt-1.jpg'
export * as dummyAvt2 from './dummy-avt-2.jpg'
export * as dummyAvt3 from './dummy-avt-3.jpg'
export * as dummyAvt4 from './dummy-avt-4.png'
export * as dummyAvt5 from './dummy-avt-5.png'
export * as dummyAvt6 from './dummy-avt-6.jpg'
export * as dummyAvt7 from './dummy-avt-7.jpg'
export * as dummyAvt8 from './dummy-avt-8.png'
export * as dummyAvtAutumn from './dummy-avt-autumn.png'
export * as dummyAvtAutumn1 from './dummy-avt-autumn-1.png'
export * as dummyAvtAutumn2 from './dummy-avt-autumn-2.png'