import dayjs from 'dayjs'
import { EEventStatus, TEvent } from '../types'

export const EVENTS: TEvent[] = [
  {
    event: `Retroactive Stage #2 - Contribute to Earn`,
    startDate: 'Sep 1, 2024',
    endDate: 'Present',
    status: EEventStatus.Upcoming,
    result: '',
  },
  {
    event: `Chūnin Program`,
    startDate: 'Apr 5, 2024',
    endDate: 'Present',
    status: EEventStatus.OnGoing,
    result: '',
  },
  {
    event: `Community Game #1 - Find & Point Out ‘Orochi'`,
    startDate: 'July 24, 2024',
    endDate: 'July 31, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `Community Game #2 - Maze Escape`,
    startDate: 'July 31, 2024',
    endDate: 'Aug 7, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `Community Game #3 Crosswords`,
    startDate: 'Aug 7, 2024',
    endDate: 'Aug 14, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `Community Game #4 - Jigsaw Puzzle`,
    startDate: 'Aug 14, 2024',
    endDate: 'Aug 21, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `Community Game #5 - Math Challenge`,
    startDate: 'Aug 22, 2024',
    endDate: 'Aug 30, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #15 - Build With The Best #9`,
    startDate: 'Aug 15, 2024',
    endDate: 'Aug 15, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #14 - Build With The Best #8`,
    startDate: 'Aug 8, 2024',
    endDate: 'Aug 8, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #13 - Build With The Best #7`,
    startDate: 'Jul 30, 2024',
    endDate: 'Jul 30, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #12 - Build With The Best #6`,
    startDate: 'Jul 18, 2024',
    endDate: 'Jul 18, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #11 - Build With the Best #5`,
    startDate: 'Jul 11, 2024',
    endDate: 'Jul 11, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #10 - Build With The Best #4`,
    startDate: 'Jul 8, 2024',
    endDate: 'Jul 8, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #9 - Build With The Best #3`,
    startDate: 'June 28, 2024',
    endDate: 'June 28, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #8 - Build With The Best #2`,
    startDate: 'June 23, 2024',
    endDate: 'June 23, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #7 - Orochi's Path Forward - Assemble`,
    startDate: 'June 14, 2024',
    endDate: 'June 14, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #6 - OROCHI 101: XORO V2 [Beta Token]`,
    startDate: 'June 3, 2024',
    endDate: 'June 3, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #5 - Build With The Best #1`,
    startDate: 'May 31, 2024',
    endDate: 'May 31, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #4 - From Zero Transaction Fee To Zero Latency Possibility`,
    startDate: 'May 15, 2024',
    endDate: 'May 15, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #3 - Verifiable Computation For Web3 Gaming | The First Step`,
    startDate: 'May 4, 2024',
    endDate: 'May 4, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #2 - Building The Zero Knowledge Modular Data Availability Layer" with our Co-founder!`,
    startDate: 'Apr 28, 2024',
    endDate: 'Apr 28, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `AMA #1 - Voice of Founding Team`,
    startDate: 'Apr 20, 2024',
    endDate: 'Apr 20, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `Retroactive Stage #1 - Return to Origin!`,
    startDate: 'Mar 25, 2024',
    endDate: 'Apr 22, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `ORO Justsu Game Night Episode #3`,
    startDate: 'May 24, 2024',
    endDate: 'May 24, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `ORO Justsu Game Night Episode #2`,
    startDate: 'May 18, 2024',
    endDate: 'May 18, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `ORO Justsu Game Night Episode #1`,
    startDate: 'May 8, 2024',
    endDate: 'May 8, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `Cooking Meme Contest`,
    startDate: 'June 19, 2024',
    endDate: 'June 30, 2024',
    status: EEventStatus.Done,
    result: '',
  },
  {
    event: `Flash Giveaway | Shukaku NFTs`,
    startDate: 'Jul 2, 2024',
    endDate: 'Jul 9, 2024',
    status: EEventStatus.Done,
    result: '',
  },
]
